### PR TITLE
Implement calling_env()

### PR DESCRIPTION
**Pull request by lionel-**
This implements a helper function that makes it easy to retrieve the original environment that called a pipe chain. This will help magrittr-aware tools to reinforce the idiom that a pipe chain is one single function entity.

Another way of implementing this would be to climb the calling stack dynamically, looking for magrittr's anchors (`_fseq`, `_function_list`, etc). This way `calling_env()` would work when called in functions embedded deeply in pipe components. If we start from `n = 5`, there would be no cost when `calling_env()` is called from the top level of a pipe component. But I suspect it may get very costly if called outside of a pipe chain and the calling stack is large.

### CODE REVIEW

**Comment by hadley** [comment]
Fixes #171

**Comment by lionel-** [comment]
We should probably use a different approach, like a marker environment installed in the data mask / exec-env. Ideally magrittr wouldn't use a child environment at all.

**Comment by smbache** [comment]
This should be so much simpler in the suggested approach where everything is evaluated in that one function

**Comment by lionel-** [comment]
I think it might make sense to evaluate magrittr expressions directly in the calling environment, I'll reply to the thread with Hadley soon!

**Pull request closed without merging**
