### PR TITLE
Add CODEOWNERS

### LINKED ISSUE #168: Add CODEOWNERS
Hi @smbache,

A heads up: at this past RStudio work week, we decided to try to formally implement "understudies" for all the packages (i.e. having a second person to help increase our code reviews, etc. — in this case, @lionel-). I'll submit a PR with a CODEOWNERS file. The link in it currently goes to nothing, but will ultimately go to a description of this process for the tidyverse.org page development practices).

Thanks,
Mara

### PR DESCRIPTION
**Pull request by batpigandme**
* Designate @smbache as primary, @lionel- as understudy
* Fixes #168

### CODE REVIEW

**Comment by stefanbache** [comment]
Looks good to me. Someone who knows what is going on with all the failing integrations should really fix them.

**Comment by batpigandme** [comment]
> Someone who knows what is going on with all the failing integrations should really fix them.
That person is definitely not me, but I will pass word along! 🙂 (cc @jimhester ?)

**Comment by batpigandme** [comment]
Whoops! Forgot to add `/.github` to `.Rbuildignore`! 😳

**Comment by hadley** [comment]
@batpigandme can you please update to new code owner style?

**Pull request closed without merging**
